version: "3.7"

services:

  mongodb:
    image: mongo:4.0.13-xenial
    container_name: soccer_data_mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./mongodata:/data/db

  scrapyd:
    build: .
    container_name: soccer_data_scrapyd
    ports:
      - "6800:6800"
    env_file: 
      - .env
    depends_on:
      - "mongodb"
    restart: always
  
  splash:
    image: scrapinghub/splash
    container_name: soccer_data_splash
    ports:
      - "8050:8050"
    depends_on:
      - "scrapyd"
    restart: always

volumes:
  mongodata: