version: "3.7"

services:

  scrapyd:
    build: .
    container_name: soccer_data_scrapyd
    ports:
      - "6800:6800"
    env_file: 
      - .env
    restart: always

  mongodb:
    image: mongo:4.0.13-xenial
    container_name: soccer_data_mongo
    env_file:
      - .env
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./mongodata:/data/db

volumes:
  mongodata: