version: "3.3"

services:

    db:
        image: postgres:12.0-alpine
        container_name: soccer_data_postgres
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - $HOME/postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        restart: always

    scrapyd:
        build: .
        container_name: soccer_data_scrapyd
        ports:
            - "6800:6800"
        env_file:
            - .env
        depends_on:
            - db
        restart: always

volumes:
    postgres_data: